package opr.client.ui;

import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HorizontalPanel;
import com.google.gwt.user.client.ui.Label;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.VerticalPanel;

public class AddView extends Composite {
	private VerticalPanel vPanel = new VerticalPanel();
	private HorizontalPanel hPanelTxt = new HorizontalPanel();
	private HorizontalPanel hPanelBoxes = new HorizontalPanel();
	Label lblID = new Label("ID - autogenerated");
	TextBox txtBoxID = new TextBox();

	public AddView(){
		this.initWidget(vPanel);
		
		hPanelTxt.add(lblID);
		hPanelBoxes.add(txtBoxID);
		vPanel.add(hPanelTxt);
		vPanel.add(hPanelBoxes);
		
		
	}

}
